"""Service layer for the AI onboarding flow."""

from datetime import datetime, timezone
from sqlalchemy.orm import Session

from app.db.base import UserProfile
from app.modules.onboarding.extraction import ProfileExtractionService
from app.modules.onboarding.models import (
    OnboardingMessage,
    OnboardingSession,
)
from app.services.llm import LLMService
from app.services.profile_service import ProfileService

ONBOARDING_SYSTEM_PROMPT = """
تو یک دستیار هوشمند، حرفه‌ای و صمیمی برای ستاپ اولیه سیستم عامل فردی (Mehr Life Time) هستی.
وظیفه تو شناخت سبک زندگی، شغل، ساعات کاری، الگوی خواب و ترجیحات کاربر است.

قوانین رفتار:
1. در هر پیام فقط یک یا نهایتاً دو سوال کوتاه، دقیق و هدفمند بپرس تا کاربر خسته نشود.
2. پاسخ‌ها را به زبان فارسی روان، محترمانه و خلاصه بنویس.
3. زمینه‌هایی که باید پوشش دهی:
   - شغل، تخصص یا زمینه تحصیلی
   - بازه ساعات کاری یا ساعات اوج تمرکز
   - بازه معمول خواب و بیداری
   - ترجیحات یا محدودیت‌های مهم در طول روز
4. پس از دریافت هر پاسخ از کاربر، بازخورد کوتاهی بده و مرحله بعد را بپرس.
5. وقتی تمام اطلاعات اساسی پوشش داده شد، خلاصه کوتاهی از شناخت خود ارائه بده و بگو آماده تحلیل و ثبت نهایی هستی.
"""


class OnboardingService:
    """Manage onboarding sessions for users."""

    def __init__(self, db: Session):
        self.db = db

    def get_active_session(
        self,
        user_id: int,
    ) -> OnboardingSession | None:
        """Return the active onboarding session for a user, if one exists."""
        return (
            self.db.query(OnboardingSession)
            .filter(
                OnboardingSession.user_id == user_id,
                OnboardingSession.status == "active",
            )
            .order_by(OnboardingSession.id.desc())
            .first()
        )

    def create_session(
        self,
        user_id: int,
    ) -> OnboardingSession:
        """Create a new active onboarding session for a user."""
        session = OnboardingSession(
            user_id=user_id,
            status="active",
        )

        self.db.add(session)
        self.db.commit()
        self.db.refresh(session)

        return session

    def get_or_create_active_session(
        self,
        user_id: int,
    ) -> OnboardingSession:
        """Return the active session or create one if it does not exist."""
        session = self.get_active_session(user_id)

        if session is not None:
            return session

        return self.create_session(user_id)

    def add_user_message(
        self,
        session_id: int,
        content: str,
    ) -> OnboardingMessage:
        """Store a message sent by the user."""
        message = OnboardingMessage(
            session_id=session_id,
            role="user",
            content=content,
        )

        self.db.add(message)
        self.db.commit()
        self.db.refresh(message)

        return message

    def add_assistant_message(
        self,
        session_id: int,
        content: str,
    ) -> OnboardingMessage:
        """Store a message generated by the AI assistant."""
        message = OnboardingMessage(
            session_id=session_id,
            role="assistant",
            content=content,
        )

        self.db.add(message)
        self.db.commit()
        self.db.refresh(message)

        return message

    def get_messages(
        self,
        session_id: int,
    ) -> list[OnboardingMessage]:
        """Return all messages in a session ordered by creation time."""
        return (
            self.db.query(OnboardingMessage)
            .filter(OnboardingMessage.session_id == session_id)
            .order_by(OnboardingMessage.created_at.asc())
            .all()
        )

    async def process_user_message(
        self,
        user_id: int,
        content: str,
        llm: LLMService | None = None,
    ) -> str:
        """
        Record the user's message in the active onboarding session, generate an AI reply,
        store it, and return the response text.
        """
        session = self.get_or_create_active_session(user_id)
        self.add_user_message(session_id=session.id, content=content)

        history_messages = self.get_messages(session.id)
        prompt_payload = [
            {"role": "system", "content": ONBOARDING_SYSTEM_PROMPT}
        ]
        for msg in history_messages:
            prompt_payload.append(
                {
                    "role": msg.role,
                    "content": msg.content,
                }
            )

        client = llm or LLMService()
        reply_text = await client.generate_response(
            messages=prompt_payload,
            temperature=0.7,
        )

        self.add_assistant_message(session_id=session.id, content=reply_text)
        return reply_text

    async def extract_profile(self, session_id: int):
        """Extract structured profile data from the onboarding conversation."""
        messages = self.get_messages(session_id)

        conversation = [
            {
                "role": message.role,
                "content": message.content,
            }
            for message in messages
        ]

        extraction_service = ProfileExtractionService(
            llm_service=LLMService()
        )

        return await extraction_service.extract(conversation)

    async def extract_and_save_profile(
        self,
        session_id: int,
    ) -> UserProfile:
        """Extract profile data via LLM and persist it directly to the user profile."""
        session = (
            self.db.query(OnboardingSession)
            .filter(OnboardingSession.id == session_id)
            .first()
        )

        if session is None:
            raise ValueError(f"Onboarding session {session_id} not found.")

        profile_data = await self.extract_profile(session_id)

        work_schedule = None
        if profile_data.work_schedule:
            start = profile_data.work_schedule.start_time
            end = profile_data.work_schedule.end_time
            if start and end:
                work_schedule = f"{start} تا {end}"
            elif start:
                work_schedule = start
            elif end:
                work_schedule = end

        sleep_schedule = None
        if profile_data.sleep_schedule:
            bedtime = profile_data.sleep_schedule.bedtime
            wake_up_time = profile_data.sleep_schedule.wake_up_time
            if bedtime and wake_up_time:
                sleep_schedule = f"{bedtime} تا {wake_up_time}"
            elif bedtime:
                sleep_schedule = bedtime
            elif wake_up_time:
                sleep_schedule = wake_up_time

        profile_service = ProfileService(self.db)
        return profile_service.update_profile(
            session.user_id,
            occupation=profile_data.occupation,
            education=profile_data.education,
            work_schedule=work_schedule,
            sleep_schedule=sleep_schedule,
            lifestyle_summary=profile_data.lifestyle_summary,
            preferences=profile_data.preferences,
            constraints=profile_data.constraints,
        )

    def update_session_stage(
        self,
        session_id: int,
        stage: str,
        topic: str | None = None,
    ) -> OnboardingSession:
        """Update the current onboarding stage and topic."""
        session = (
            self.db.query(OnboardingSession)
            .filter(OnboardingSession.id == session_id)
            .first()
        )

        if session is None:
            raise ValueError(f"Onboarding session {session_id} not found.")

        session.current_stage = stage
        session.last_topic = topic

        self.db.commit()
        self.db.refresh(session)

        return session

    def complete_session(
        self,
        session_id: int,
    ) -> OnboardingSession:
        """Mark an onboarding session as completed."""
        session = (
            self.db.query(OnboardingSession)
            .filter(OnboardingSession.id == session_id)
            .first()
        )

        if session is None:
            raise ValueError(f"Onboarding session {session_id} not found.")

        session.status = "completed"
        session.completed_at = datetime.now(timezone.utc)

        self.db.commit()
        self.db.refresh(session)

        return session
